services:
  service_app:
    restart: always
    image: "issamjh/snt:latest"
    depends_on:
      - mysqldb

    ports:
      - 9080:9080
      - 9000-9080:9080
      - :9080


    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/${MYSQL_DATABASE:-sakila}
      - spring.datasource.username=${MYSQL_USER:-admin}
      - spring.datasource.password=${MYSQL_PASSWORD:-admin}

  mysqldb:
    container_name: mysqldb
    restart: always
    image: "mysql"
    ports:
      - 3307-3333:3306
    volumes:
      # - ./docker-scripts:/docker-entrypoint-initdb.d:rw
      # - ./mysql-data:/var/lib/mysql:rw
      - ./sakila.sql:/docker-entrypoint-initdb.d/sakila.sql:ro


    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE:-sakila}"
      MYSQL_USER: "${MYSQL_USER:-admin}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD:-admin}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD:-root}"

