services:
  service_app:
    restart: always
    image: "issamjh/snt:latest"
    depends_on:
      - mysqldb

    ports:
      - 9080:9080
      - 9000-9080:9080
      - :9080
    #expose: #NECESSARY TO INTERNAL C0COMMUNICATION AMONG SERVICES OF THE CONTAINER
    #  - 3306
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/sakila


  mysqldb:
    restart: always
    image: "mysql"
    ports:
      - :3306
    volumes:
      - ./docker-scripts:/docker-entrypoint-initdb.d:rw
      - ./mysql-data:/var/lib/mysql:rw
      - ./sakila.sql:/docker-entrypoint-initdb.d/sakila.sql
    #expose: #NECESSARY TO INTERNAL C0COMMUNICATION AMONG SERVICES OF THE CONTAINER
    #  - 3306
    environment:
      MYSQL_DATABASE: sakila
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root

